version: 2.1
executors:
  exectr:
    docker:
      - image: mustaphaaref/cppcmakegtest:latest

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            mkdir -p build && cd build
            cmake ..
            make

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
